# Generated by Django 5.2.7 on 2025-10-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuserm',
            name='role',
            field=models.CharField(choices=[('client_root_admin', 'client_root_admin'), ('client_admin', 'client_admin'), ('client_user', 'client_user')], db_index=True, max_length=20),
        ),
    ]
