# Generated by Django 5.2.7 on 2025-10-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_clientuserm_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuserm',
            name='is_root_client_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientuserm',
            name='role',
            field=models.CharField(choices=[('client_admin', 'client_admin'), ('client_user', 'client_user')], db_index=True, max_length=20),
        ),
    ]
