# Generated by Django 5.2.7 on 2025-10-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_clientuserm_is_root_client_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuserm',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
