# Generated by Django 5.2.7 on 2025-10-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_clientuserm_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientuserm',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clientuserm',
            name='name',
        ),
    ]
