# Generated by Django 5.2.7 on 2025-10-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_clientuserm_email_remove_clientuserm_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientuserm',
            name='status',
        ),
    ]
